name: Deploy Kafka to EC2

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REMOTE_STACK_DIR: /home/${{ secrets.EC2_USER }}/stacks/kafka

jobs:
  deploy-kafka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure remote dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ${{ env.REMOTE_STACK_DIR }}

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "${{ env.REMOTE_STACK_DIR }}"

      - name: Launch / update Kafka stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: "10m"
          script: |
            set -e
            cd ${{ env.REMOTE_STACK_DIR }}

            docker container prune -f || true
            docker image prune -af || true
            docker volume prune -f || true

            # Pull and recreate using available compose command
            if command -v docker-compose >/dev/null 2>&1; then
              docker-compose pull
              docker-compose up -d
              docker-compose ps
            else
              docker compose pull
              docker compose up -d
              docker compose ps
            fi
