name: Deploy Kafka to EC2

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REMOTE_STACK_DIR: ~/stacks/kafka

jobs:
  deploy-kafka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "back/kafka/docker-compose.yml"
          target: ${{ env.REMOTE_STACK_DIR }}

      - name: Ensure remote dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/stacks/kafka

      - name: Launch / update Kafka stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: "10m"
          script: |
            set -e
            cd ~/stacks/kafka

            docker container prune -f || true
            docker image prune -af || true
            docker volume prune -f || true

            # Pull and recreate using available compose command
            (docker compose pull || docker-compose pull)
            (docker compose up -d || docker-compose up -d)

            (docker compose ps || docker-compose ps)
